#!/usr/bin/env bash

cd `dirname $0`

case "$1" in

	"vim")
		mkdir -p ./.vim/bundle
		git clone https://github.com/VundleVim/Vundle.vim.git ./.vim/bundle/Vundle.vim
		ln -s $(pwd)/.vim $HOME/.vim
		vim +PluginInstall +qall
		;;

	"zsh")
		DEST=$HOME/.zshrc
		rm $DEST
		ln -s $(pwd)/zsh/.zshrc $DEST
		;;


	"sublime")
		DEST_DIR=$HOME/.config/sublime-text-3/Packages
		DEST=$DEST_DIR/User
		rm -rf $DEST
		mkdir -p $DEST_DIR
		ln -s $(pwd)/subl $DEST
		;;

	"gitconfig")
		DEST=$HOME/.gitconfig
		rm -rf $DEST
		ln -s $(pwd)/.gitconfig $DEST
		;;

	"gitignore")
		DEST=$HOME/.gitignore-global
		rm -rf $DEST
		ln -s $(pwd)/.gitignore-global $DEST
		;;

	*)
		echo $1
		;;
esac
